apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2023-09-17T21:56:55Z"
  labels:
    app: istio-ingressgateway
    install.operator.istio.io/owning-resource: installed-state
    install.operator.istio.io/owning-resource-namespace: istio-system
    istio: ingressgateway
    istio.io/rev: default
    operator.istio.io/component: IngressGateways
    operator.istio.io/managed: Reconcile
    operator.istio.io/version: 1.19.0
    release: istio
  name: istio-ingressgateway
  namespace: istio-system
  resourceVersion: "3756"
  uid: 96ab563f-a720-4fb9-874c-0e4f382c740f
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.101.94.174
  clusterIPs:
  - 10.101.94.174
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: status-port
    nodePort: 32365
    port: 15021
    protocol: TCP
    targetPort: 15021
  - name: http2
    nodePort: 31627
    port: 80
    protocol: TCP
    targetPort: 8080
  - name: https
    nodePort: 30233
    port: 443
    protocol: TCP
    targetPort: 8443
  - name: http-server
    nodePort: 31628
    port: 8000
    protocol: TCP
  - name: http-admin
    nodePort: 31629
    port: 3901
    protocol: TCP
  selector:
    app: istio-ingressgateway
    istio: ingressgateway
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 10.101.94.174
